mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
    path("search/", include("search.urls"))
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/search/urls.py
from django.urls import path
from . import views

app_name = "search"
urlpatterns = [
    path("", views.search_ex, name="search-ex"),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Service(models.Model):
    name = models.CharField(max_length=100)
    organiser = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    def __str__(self):
        return self.name

mysite/search/models.py
from django.db import models

# Create your models here.

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.db import connection
from . import views
from django.urls import path, reverse
from .models import Question 
from django.template import loader  
from django.shortcuts import render
from .models import Question, Choice
from django.views import generic
from django.utils import timezone

# Create your views here.
def get_queryset(self):
    """
    Return the last five published questions (not including those set to be
    published in the future).
    """
    return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
        :5
    ]

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]
    

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))





# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     template = loader.get_template("polls/index.html")
#     context = {
#         "latest_question_list": latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))

# Or use render to display the list
# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     context = {"latest_question_list": latest_question_list}
#     return render(request, "polls/index.html", context)
# # we use render if we just want a straight forward rendering without much control over it

# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." % question_id)


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/results.html", {"question": question})

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/detail.html", {"question": question})

mysite/search/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.db import connection
from . import views
from django.urls import path, reverse
from polls.models import Service
from django.template import loader  
from django.shortcuts import render
from polls.models import Question, Choice
from django.views import generic
from django.utils import timezone
import Levenshtein

def search_ex(request):
    #if request.method == "POST":
    correct_words = ['pelerinaj', 'manastirile', 'rupestre', 'grup', 'dezvoltare', 'personala', 'socio-emotionala', 'emotionala', 'sedinta', 'terapie', 'psihologica', 'clinica', 'individuala', 'cuplu', 'familie', 'culinara', 'coaching', 'nutritie']
    if 'searched' in request.POST:
        services = Service.objects.none()
        searched = str(request.POST['searched'])
        for word in searched.split(" "):
              if word not in ['de','la','cu','pentru','De', 'La', 'Cu', 'Pentru', 'in', 'In']:
                    wordd = word[:] 
                    newword = min(correct_words, key=lambda x: Levenshtein.distance(word, x))
                    wordlower = newword[0].lower() + newword[1:]
                    wordupper = newword[0].upper() + newword[1:]
                    services1 = Service.objects.filter(name__contains = wordlower)
                    services2 = Service.objects.filter(name__contains = wordupper)
                    services |= services1 
                    services |= services2
                    wordlower = wordd[0].lower() + wordd[1:]
                    wordupper = wordd[0].upper() + wordd[1:]
                    services1 = Service.objects.filter(name__contains = wordlower)
                    services2 = Service.objects.filter(name__contains = wordupper)
                    services |= services1 
                    services |= services2

        return render(request, 
                       'search/search-ex.html',
                        {'searched':searched,
                         'services':services}
                )
    else:
        return render(request, 
                    'search/search-ex.html',
                    {}
        )
         


mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
    <form class = "d-flex" method = POST  action = "{% url 'search:search-ex' %}" > 
        {% csrf_token %}
        <input class = "form-control me-2" type = "search" placeholder = "Search" aria-label="Search" name = "searched">
        <button class = "btn btn-outline-secondary" type = "submit">Search</button>
    </form>
{% else %}
    <p>No polls are available.</p>


{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/search/templates/search/search-ex.html
{% block content %}
    <center>
    {%if searched %}
        <h1>You searched for {{searched}}</h1>
        <br/>
        {% for service in services %}
            {{ service }} <br/>
        {% endfor %}
    {% else %}
        <h1>You forgot to search</h1>

    {% endif %}
    </center>
{% endblock %}